// Mocks generated by Mockito 5.4.6 from annotations
// in plop/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i8;

import 'package:hive_ce/hive.dart' as _i2;
import 'package:http/http.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:plop/core/models/contact_model.dart' as _i6;
import 'package:plop/core/models/message_model.dart' as _i10;
import 'package:plop/core/models/user_model.dart' as _i7;
import 'package:plop/core/services/database_service.dart' as _i11;
import 'package:plop/core/services/invitation_service.dart' as _i12;
import 'package:plop/core/services/notification_service.dart' as _i9;
import 'package:plop/core/services/user_service.dart' as _i3;
import 'package:plop/core/services/websocket_service.dart' as _i14;
import 'package:shared_preferences/shared_preferences.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i3.UserService {
  @override
  bool get isGlobalMute => (super.noSuchMethod(
        Invocation.getter(#isGlobalMute),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set userId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set username(String? value) => super.noSuchMethod(
        Invocation.setter(
          #username,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isGlobalMute(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isGlobalMute,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> init({_i5.SharedPreferences? prefs}) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#prefs: prefs},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool hasUser() => (super.noSuchMethod(
        Invocation.method(
          #hasUser,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<bool> createUser(String? newUsername) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [newUsername],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> updateUsername(
    String? newUsername, {
    _i5.SharedPreferences? prefs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUsername,
          [newUsername],
          {#prefs: prefs},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserId(String? newUserId) => (super.noSuchMethod(
        Invocation.method(
          #updateUserId,
          [newUserId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleGlobalMute({_i5.SharedPreferences? prefs}) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleGlobalMute,
          [],
          {#prefs: prefs},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> syncContactsPseudos(List<_i6.Contact>? localContacts) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncContactsPseudos,
          [localContacts],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i7.User?> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i4.Future<_i7.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.User?>.value(),
      ) as _i4.Future<_i7.User?>);

  @override
  _i4.Future<void> saveUser(_i7.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getFcmToken() => (super.noSuchMethod(
        Invocation.method(
          #getFcmToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i9.NotificationService {
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> checkNotificationFromTerminatedState() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkNotificationFromTerminatedState,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendFcmTokenToServer(String? token) => (super.noSuchMethod(
        Invocation.method(
          #sendFcmTokenToServer,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showNotification(_i10.MessageModel? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [message],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i11.DatabaseService {
  @override
  _i2.Box<_i6.Contact> get contactsBox => (super.noSuchMethod(
        Invocation.getter(#contactsBox),
        returnValue: _FakeBox_0<_i6.Contact>(
          this,
          Invocation.getter(#contactsBox),
        ),
        returnValueForMissingStub: _FakeBox_0<_i6.Contact>(
          this,
          Invocation.getter(#contactsBox),
        ),
      ) as _i2.Box<_i6.Contact>);

  @override
  _i2.Box<_i10.MessageModel> get messagesBox => (super.noSuchMethod(
        Invocation.getter(#messagesBox),
        returnValue: _FakeBox_0<_i10.MessageModel>(
          this,
          Invocation.getter(#messagesBox),
        ),
        returnValueForMissingStub: _FakeBox_0<_i10.MessageModel>(
          this,
          Invocation.getter(#messagesBox),
        ),
      ) as _i2.Box<_i10.MessageModel>);

  @override
  _i2.Box<dynamic> get settingsBox => (super.noSuchMethod(
        Invocation.getter(#settingsBox),
        returnValue: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#settingsBox),
        ),
        returnValueForMissingStub: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#settingsBox),
        ),
      ) as _i2.Box<dynamic>);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addContact(_i6.Contact? contact) => (super.noSuchMethod(
        Invocation.method(
          #addContact,
          [contact],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addMessage(_i10.MessageModel? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMessage,
          [message],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.Contact?> getContact(String? contactId) => (super.noSuchMethod(
        Invocation.method(
          #getContact,
          [contactId],
        ),
        returnValue: _i4.Future<_i6.Contact?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.Contact?>.value(),
      ) as _i4.Future<_i6.Contact?>);

  @override
  _i4.Future<_i10.MessageModel?> getMessage(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessage,
          [messageId],
        ),
        returnValue: _i4.Future<_i10.MessageModel?>.value(),
        returnValueForMissingStub: _i4.Future<_i10.MessageModel?>.value(),
      ) as _i4.Future<_i10.MessageModel?>);

  @override
  _i4.Future<List<_i6.Contact>> getAllContacts() => (super.noSuchMethod(
        Invocation.method(
          #getAllContacts,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Contact>>.value(<_i6.Contact>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.Contact>>.value(<_i6.Contact>[]),
      ) as _i4.Future<List<_i6.Contact>>);

  @override
  _i4.Future<List<_i6.Contact>> getAllContactsOrdered() => (super.noSuchMethod(
        Invocation.method(
          #getAllContactsOrdered,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Contact>>.value(<_i6.Contact>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.Contact>>.value(<_i6.Contact>[]),
      ) as _i4.Future<List<_i6.Contact>>);

  @override
  _i4.Future<List<_i10.MessageModel>> getMessagesForContact(
          String? contactId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesForContact,
          [contactId],
        ),
        returnValue:
            _i4.Future<List<_i10.MessageModel>>.value(<_i10.MessageModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i10.MessageModel>>.value(<_i10.MessageModel>[]),
      ) as _i4.Future<List<_i10.MessageModel>>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [InvitationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationService extends _i1.Mock implements _i12.InvitationService {
  @override
  _i4.Future<Map<String, dynamic>?> createInvitationCode(
    String? userId,
    String? userPseudo, {
    _i13.Client? client,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvitationCode,
          [
            userId,
            userPseudo,
          ],
          {#client: client},
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, String>?> useInvitationCode(
    String? code,
    String? myUserId,
    String? myPseudo, {
    _i13.Client? client,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #useInvitationCode,
          [
            code,
            myUserId,
            myPseudo,
          ],
          {#client: client},
        ),
        returnValue: _i4.Future<Map<String, String>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, String>?>.value(),
      ) as _i4.Future<Map<String, String>?>);
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i14.WebSocketService {
  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void connect() => super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendMessage(
    String? recipientId,
    String? text, {
    String? tempId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            recipientId,
            text,
          ],
          {#tempId: tempId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void syncClientData() => super.noSuchMethod(
        Invocation.method(
          #syncClientData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void requestSync() => super.noSuchMethod(
        Invocation.method(
          #requestSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendReadConfirmation(String? messageId) => super.noSuchMethod(
        Invocation.method(
          #sendReadConfirmation,
          [messageId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> updateContactLastMessageStatus(
    String? contactId,
    _i6.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContactLastMessageStatus,
          [
            contactId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> checkSentMessageStatus(String? contactId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkSentMessageStatus,
          [contactId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
