services:
  compile-windows:
    build:
      context: .
      dockerfile: Dockerfile.windows
      args:
        PRODUCTION: "true"
        BASE_URL: ${BASE_URL}
        WEBSOCKET_URL: ${WEBSOCKET_URL}
#    volumes:
#      - ./build_output:/app:ro
