services:
  site:
    image: registry.profluens.com/plop_site
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        PRODUCTION: "true"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '10'
    ports:
      - "80:80"
  service:
    image: registry.profluens.com/plop_service
    build:
      dockerfile: Dockerfile
      context: server
      args:
        PRODUCTION: "true"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '10'
    env_file:
      - server/.env
    ports:
      - "8080:8080"
