services:
  compile-android:
    build:
      context: .
      dockerfile: Dockerfile.android
      args:
        PRODUCTION: "true"
        BASE_URL: ${BASE_URL}
        WEBSOCKET_URL: ${WEBSOCKET_URL}
        SUBVERSION: ${SUBVERSION}
#    volumes:
#      - ./build_output:/app


#  docker compose  -f docker-compose-build-android.yml create
#  docker compose cp compile-android:/app/app-release.apk ./build_output
# docker compose cp compile-android:/app/app-release.apk ./build_output/plop-release.apk
