# Définition des services (conteneurs) que nous voulons lancer.
services:
  # Nom de notre service. Vous pouvez l'appeler comme vous voulez.
  plop-server:
    # 'build: .' indique à Docker Compose de construire l'image
    # en utilisant le Dockerfile.android-linux qui se trouve dans le répertoire courant (.).
    build: .
    # Nom que l'on donne au conteneur une fois qu'il est lancé.
    container_name: plop_server_container
    # Mappage des ports. On mappe le port 8080 de la machine hôte
    # au port 8080 à l'intérieur du conteneur.
    ports:
      - "8080:8080"
    # 'restart: unless-stopped' redémarrera automatiquement le conteneur
    # s'il s'arrête de manière inattendue, sauf si vous l'arrêtez manuellement.
    restart: unless-stopped
    environment:
      - DEBUG=true
