// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-jb5CUIR60W-uo_XPnLyJd6W27n_LqA',
    appId: '1:522673950816:web:491fee6dd38614084a3305',
    messagingSenderId: '522673950816',
    projectId: 'plop-20277',
    authDomain: 'plop-20277.firebaseapp.com',
    storageBucket: 'plop-20277.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTQ393946KC_7VY3X6hvUcbGFR29zT_KM',
    appId: '1:522673950816:android:1bfaae82253a48614a3305',
    messagingSenderId: '522673950816',
    projectId: 'plop-20277',
    storageBucket: 'plop-20277.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1q88TTR8-enA1BBIlC3F68QQJ1ILW4I',
    appId: '1:522673950816:ios:7e869106796b4b844a3305',
    messagingSenderId: '522673950816',
    projectId: 'plop-20277',
    storageBucket: 'plop-20277.firebasestorage.app',
    iosBundleId: 'com.quickcontest.plop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd1q88TTR8-enA1BBIlC3F68QQJ1ILW4I',
    appId: '1:522673950816:ios:7e869106796b4b844a3305',
    messagingSenderId: '522673950816',
    projectId: 'plop-20277',
    storageBucket: 'plop-20277.firebasestorage.app',
    iosBundleId: 'com.quickcontest.plop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_-jb5CUIR60W-uo_XPnLyJd6W27n_LqA',
    appId: '1:522673950816:web:85ad5a5ec5a9836f4a3305',
    messagingSenderId: '522673950816',
    projectId: 'plop-20277',
    authDomain: 'plop-20277.firebaseapp.com',
    storageBucket: 'plop-20277.firebasestorage.app',
  );
}
