// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:plop/core/models/contact_model.dart';
import 'package:plop/core/models/message_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ContactAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(MessageStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ContactAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(MessageStatusAdapter());
  }
}
