# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Build & Release Windows App

# Déclencheurs du workflow
on:
  # Se lance à chaque push sur la branche "main" ou "master"
  push:
    branches:
      - main
      - master
  # Permet de lancer manuellement le workflow depuis l'interface de GitHub
  workflow_dispatch:

jobs:
  build-and-release-windows:
    # Nom du job
    name: Build and Release for Windows
    # Utilise une machine virtuelle Windows, qui inclut déjà Visual Studio.
    runs-on: windows-latest

    # Donne la permission au workflow de créer une Release
    permissions:
      contents: write

    env:
      # ATTENTION: Remplacez les URLs ci-dessous par vos véritables URLs de production.
      BASE_URL: "https://ws.plop.quickcontest.com"
      WEBSOCKET_URL: "wss://ws.plop.quickcontest.com"

    steps:
      # 1. Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Version
        run : |
          (Get-Content -Path pubspec.yaml -Raw) -replace  '^(version: [0-9]+\.[0-9]+\.).*', "`$1${{ github.run_number }}" | Set-Content -Path pubspec.yaml
        shell: pwsh
      - name: Set Firebase Settings (PowerShell)
        run: |
          # 1. Renommer le fichier template
          $templatePath = "lib\firebase_options.template.dart"
          $targetPath = "lib\firebase_options.dart"
          Move-Item -Path $templatePath -Destination $targetPath
          
          # 2. Lire le contenu du fichier une seule fois
          $fileContent = Get-Content -Path $targetPath -Raw
          
          # 3. Effectuer tous les remplacements en mémoire
          $fileContent = $fileContent -replace '___FIREBASE_API_KEY_WEB___', '${{ secrets.FIREBASE_API_KEY_WEB }}'
          $fileContent = $fileContent -replace '___FIREBASE_APP_ID_WEB___', '${{ secrets.FIREBASE_APP_ID_WEB }}'
          $fileContent = $fileContent -replace '___FIREBASE_API_KEY_ANDROID___', '${{ secrets.FIREBASE_API_KEY_ANDROID }}'
          $fileContent = $fileContent -replace '___FIREBASE_APP_ID_ANDROID___', '${{ secrets.FIREBASE_APP_ID_ANDROID }}'
          $fileContent = $fileContent -replace '___FIREBASE_API_KEY_IOS___', '${{ secrets.FIREBASE_API_KEY_IOS }}'
          $fileContent = $fileContent -replace '___FIREBASE_APP_ID_IOS___', '${{ secrets.FIREBASE_APP_ID_IOS }}'
          $fileContent = $fileContent -replace '___FIREBASE_API_KEY_WINDOWS___', '${{ secrets.FIREBASE_API_KEY_WINDOWS }}'
          $fileContent = $fileContent -replace '___FIREBASE_APP_ID_WINDOWS___', '${{ secrets.FIREBASE_APP_ID_WINDOWS }}'
          $fileContent = $fileContent -replace '___FIREBASE_PROJECT_ID___', '${{ secrets.FIREBASE_PROJECT_ID }}'
          $fileContent = $fileContent -replace '___FIREBASE_MESSAGING_SENDER_ID___', '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'
          
          
          # 4. Écrire le contenu final dans le fichier une seule fois
          $fileContent | Set-Content -Path $targetPath
        shell: pwsh
      # 2. Installation et configuration de Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Run Flutter tests
        run: flutter test



      # 3. Activation du support pour le bureau Windows
      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      # 4. Téléchargement des dépendances du projet
      - name: Get Flutter dependencies
        run: flutter pub get

      # 5. Compilation de l'application Windows
      # Le runner 'windows-latest' a déjà les outils de build Visual Studio nécessaires.
      - name: Build Windows application
        run: |
          flutter build windows --release `
            --dart-define=BASE_URL=${{ env.BASE_URL }} `
            --dart-define=WEBSOCKET_URL=${{ env.WEBSOCKET_URL }}

      # 6. Compression du dossier de la release en .zip
      # Le résultat du build est un dossier complet, on le compresse pour la distribution.
      - name: Zip Release folder
        run: powershell Compress-Archive -Path ./build/windows/x64/runner/Release/* -DestinationPath ./plop-windows-release.zip

      # 7. Publication du .zip dans une Release GitHub
      - name: Create GitHub Release and Upload Zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build
          name: Latest Windows Build
          prerelease: true
          files: ./plop-windows-release.zip

